---
- hosts: 172.31.30.64
  become: yes
  tasks:
   - name: i want to execute linux command
     command: hastname -f
     register: myresult
     
   - name: i want display myresult
     debug:
        msg: "{{myresult}}"   

