---
- hosts: 172.31.5.86
  become: yes
  vars: 
    myvars01: git
    myvars02: wget
    myvars03: tree
  tasks:
   - name: i want to display 
     debug:
        msg: git  

   - name: i want to install tree
     apt:
       name: tree
       state: present
             